apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: autoscalers.pks.pivotal.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: pks.pivotal.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            enabled:
              type: boolean
            index:
              type: string
              enum: 
              - cpu
              - memory
            image:
              type: string
            upscaleon:
              type: integer
              minimum: 20
              maximum: 100
            downscaleon:
              type: integer
              minimum: 0
              maximum: 80
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: autoscalers
    # singular name to be used as an alias on the CLI and for display
    singular: autoscaler
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: AutoScaler
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - as
