# Default values for pks-autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scaler1:
  name: "cpuscaler"
  enabled: false
  index: "cpu"
  image: "ccr.ccs.tencentyun.com/yanghaitao/autoscaler:v0.1"
  upscaleon: 80
  downscaleon: 20

scaler2:
  name: "memoryscaler"
  enabled: false
  index: "memory"
  image: "ccr.ccs.tencentyun.com/yanghaitao/autoscaler:v0.1"
  upscaleon: 80
  downscaleon: 20

secret: 
  name: "imagepullsecret"
  username: "MTAwMDEyOTA3Njk1"
  password: "Qm9zdG9uMTk3OQ=="

deployment:
  name: "autoscaler"
  container:
    name: "autoscaler"
    image: "ccr.ccs.tencentyun.com/yanghaitao/autoscaler:v0.1"
    port: 80

service:
  port: 80
